[package]
name = "heartbeat"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
crc = "3.0.0"
futures = "0.3.24"
spinoff = "0.5.3"
uuid = "1.1.2"

[dependencies.toio]
version = 1.21.0
features = ["full"]

[dependencies.bluer]
version = "0.15.0"
features = [ "bluetoothd" ]
