[package]
name = "heartbeat"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.10.0"
chrono = "0.4.22"
crc = "3.0.0"
futures = "0.3.24"
lazy_static = "1.4.0"
spinoff = "0.5.3"
tokio = { version = "1.21.0", features = ["full"] }
uuid = "1.1.2"
# phf = { version = "0.11.1", features = ["macros"] }
